INSERT INTO public.activities (name, body_parts, types) VALUES
  ('Rest', ARRAY['other']::text[], ARRAY['other']::text[]),
  ('Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Wide Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Diamond Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Decline Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Incline Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Knee Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Pike Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Hindu Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Clap Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics','cardio']::text[]),
  ('Spider-Man Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Archer Push-ups', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Pull-ups', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Chin-ups', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Wide-grip Pull-ups', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Negative Pull-ups', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Australian Rows', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Inverted Rows', ARRAY['arms','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Dips', ARRAY['arms','chest']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Bench Dips', ARRAY['arms']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Tricep Dips', ARRAY['arms']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Bicep Curls', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Hammer Curls', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Tricep Extensions', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Tricep Kickbacks', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Skull Crushers', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Shoulder Press', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Overhead Press', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Arnold Press', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Lateral Raises', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Front Raises', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Rear Delt Flies', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Upright Rows', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Shrugs', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Wrist Curls', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Reverse Wrist Curls', ARRAY['arms']::text[], ARRAY['resistance']::text[]),
  ('Squats', ARRAY['legs','full body']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Bodyweight Squats', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Goblet Squats', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Sumo Squats', ARRAY['legs']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Jump Squats', ARRAY['legs','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Pistol Squats', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Bulgarian Split Squats', ARRAY['legs']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Split Squats', ARRAY['legs']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Cossack Squats', ARRAY['legs']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Wall Sit', ARRAY['legs']::text[], ARRAY['isometric']::text[]),
  ('Lunges', ARRAY['legs']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Forward Lunges', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Reverse Lunges', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Walking Lunges', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Lateral Lunges', ARRAY['legs']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Curtsy Lunges', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Jumping Lunges', ARRAY['legs','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Step-ups', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Box Jumps', ARRAY['legs','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Calf Raises', ARRAY['legs']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Single-leg Calf Raises', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Donkey Calf Raises', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Glute Bridges', ARRAY['legs','core']::text[], ARRAY['calisthenics','resistance']::text[]),
  ('Single-leg Glute Bridge', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Hip Thrusts', ARRAY['legs','core']::text[], ARRAY['calisthenics','resistance']::text[]),
  ('Frog Pumps', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Fire Hydrants', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Donkey Kicks', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Romanian Deadlifts', ARRAY['legs','back']::text[], ARRAY['resistance']::text[]),
  ('Deadlifts', ARRAY['full body','back','legs']::text[], ARRAY['resistance']::text[]),
  ('Sumo Deadlifts', ARRAY['legs','back']::text[], ARRAY['resistance']::text[]),
  ('Single-leg Deadlifts', ARRAY['legs','back']::text[], ARRAY['resistance','calisthenics']::text[]),
  ('Good Mornings', ARRAY['legs','back']::text[], ARRAY['resistance']::text[]),
  ('Hip Abductions', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Hip Adductions', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Leg Curls', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Leg Extensions', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Leg Press', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Plank', ARRAY['core','full body']::text[], ARRAY['isometric']::text[]),
  ('High Plank', ARRAY['core','arms']::text[], ARRAY['isometric']::text[]),
  ('Side Plank', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Reverse Plank', ARRAY['core','arms']::text[], ARRAY['isometric']::text[]),
  ('Plank Up-downs', ARRAY['core','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Plank Shoulder Taps', ARRAY['core','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Plank Jacks', ARRAY['core','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Plank Hip Dips', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Forearm Plank', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Sit-ups', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Reverse Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Bicycle Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Russian Twists', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('V-ups', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Toe Touches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Leg Raises', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Hanging Leg Raises', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Flutter Kicks', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Scissor Kicks', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Mountain Climbers', ARRAY['core','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Cross-body Mountain Climbers', ARRAY['core','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Dead Bug', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Bird Dog', ARRAY['core','back']::text[], ARRAY['calisthenics']::text[]),
  ('Hollow Hold', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Hollow Rocks', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Superman', ARRAY['back','core']::text[], ARRAY['calisthenics','isometric']::text[]),
  ('Superman Hold', ARRAY['back','core']::text[], ARRAY['isometric']::text[]),
  ('Y-T-W Raises', ARRAY['back']::text[], ARRAY['calisthenics']::text[]),
  ('Cobra Pose', ARRAY['back','core']::text[], ARRAY['yoga','mobility']::text[]),
  ('Cat-Cow', ARRAY['back','core']::text[], ARRAY['yoga','mobility']::text[]),
  ('Bridge Pose', ARRAY['back','core','legs']::text[], ARRAY['yoga','mobility']::text[]),
  ('L-sit', ARRAY['core','arms']::text[], ARRAY['isometric']::text[]),
  ('Tuck Hold', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Boat Pose', ARRAY['core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Bear Crawl', ARRAY['full body','core']::text[], ARRAY['calisthenics']::text[]),
  ('Crab Walk', ARRAY['full body','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Inchworm', ARRAY['full body','core']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Burpees', ARRAY['full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Half Burpees', ARRAY['full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Squat Thrusts', ARRAY['full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Jumping Jacks', ARRAY['full body']::text[], ARRAY['cardio']::text[]),
  ('Star Jumps', ARRAY['full body']::text[], ARRAY['cardio']::text[]),
  ('Seal Jumps', ARRAY['full body']::text[], ARRAY['cardio']::text[]),
  ('High Knees', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Butt Kicks', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Skater Jumps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Tuck Jumps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Jumping Rope', ARRAY['full body']::text[], ARRAY['cardio']::text[]),
  ('Shadow Boxing', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Running in Place', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Jogging in Place', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Sprints', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Lateral Shuffles', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Jump Rope Doubles', ARRAY['full body']::text[], ARRAY['cardio']::text[]),
  ('Squat Jumps', ARRAY['legs','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Burpee Pull-ups', ARRAY['full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Thrusters', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Clean and Press', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Kettlebell Swings', ARRAY['full body','back']::text[], ARRAY['resistance','cardio']::text[]),
  ('Goblet Carry', ARRAY['full body','core']::text[], ARRAY['resistance']::text[]),
  ('Farmer''s Walk', ARRAY['full body','arms']::text[], ARRAY['resistance']::text[]),
  ('Suitcase Carry', ARRAY['full body','core']::text[], ARRAY['resistance']::text[]),
  ('Turkish Get-up', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Bent-over Rows', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Single-arm Rows', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('T-bar Rows', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Seated Rows', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Lat Pulldowns', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Face Pulls', ARRAY['arms','back']::text[], ARRAY['resistance']::text[]),
  ('Bench Press', ARRAY['arms','chest']::text[], ARRAY['resistance']::text[]),
  ('Incline Bench Press', ARRAY['arms','chest']::text[], ARRAY['resistance']::text[]),
  ('Decline Bench Press', ARRAY['arms','chest']::text[], ARRAY['resistance']::text[]),
  ('Dumbbell Press', ARRAY['arms','chest']::text[], ARRAY['resistance']::text[]),
  ('Dumbbell Flies', ARRAY['chest']::text[], ARRAY['resistance']::text[]),
  ('Cable Crossovers', ARRAY['chest']::text[], ARRAY['resistance']::text[]),
  ('Pec Deck', ARRAY['chest']::text[], ARRAY['resistance']::text[]),
  ('Chest Squeeze', ARRAY['chest']::text[], ARRAY['isometric']::text[]),
  ('Wall Push', ARRAY['chest']::text[], ARRAY['isometric']::text[]),
  ('Neck Rolls', ARRAY['other']::text[], ARRAY['mobility']::text[]),
  ('Shoulder Rolls', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Arm Circles', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Wrist Circles', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Hip Circles', ARRAY['legs','core']::text[], ARRAY['mobility']::text[]),
  ('Ankle Circles', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Leg Swings', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Side Leg Swings', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Torso Twists', ARRAY['core']::text[], ARRAY['mobility']::text[]),
  ('Side Bends', ARRAY['core']::text[], ARRAY['mobility']::text[]),
  ('Standing Forward Fold', ARRAY['back','legs']::text[], ARRAY['mobility']::text[]),
  ('Seated Forward Fold', ARRAY['back','legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Butterfly Stretch', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Pigeon Pose', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Pigeon Stretch', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Lizard Pose', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Frog Stretch', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Hip Flexor Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Quad Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Hamstring Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Calf Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Glute Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Figure Four Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Child''s Pose', ARRAY['back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Downward Dog', ARRAY['full body']::text[], ARRAY['mobility','yoga']::text[]),
  ('Upward Dog', ARRAY['core','back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Cobra Stretch', ARRAY['core','back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Sphinx Pose', ARRAY['core','back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Camel Pose', ARRAY['core','back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Seated Twist', ARRAY['core']::text[], ARRAY['mobility','yoga']::text[]),
  ('Supine Twist', ARRAY['core','back']::text[], ARRAY['mobility','yoga']::text[]),
  ('Thread the Needle', ARRAY['back','arms']::text[], ARRAY['mobility','yoga']::text[]),
  ('World''s Greatest Stretch', ARRAY['full body']::text[], ARRAY['mobility']::text[]),
  ('Doorway Stretch', ARRAY['chest','arms']::text[], ARRAY['mobility']::text[]),
  ('Wall Slides', ARRAY['back','arms']::text[], ARRAY['mobility']::text[]),
  ('Cross-body Shoulder Stretch', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Tricep Stretch', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Wrist Stretch', ARRAY['arms']::text[], ARRAY['mobility']::text[]),
  ('Neck Stretch', ARRAY['other']::text[], ARRAY['mobility']::text[]),
  ('Standing Side Stretch', ARRAY['core']::text[], ARRAY['mobility']::text[]),
  ('Cat Stretch', ARRAY['back']::text[], ARRAY['mobility']::text[]),
  ('Cow Stretch', ARRAY['back']::text[], ARRAY['mobility']::text[]),
  ('Mountain Pose', ARRAY['full body']::text[], ARRAY['yoga']::text[]),
  ('Tree Pose', ARRAY['legs','core']::text[], ARRAY['yoga']::text[]),
  ('Warrior I', ARRAY['legs','full body']::text[], ARRAY['yoga']::text[]),
  ('Warrior II', ARRAY['legs','full body']::text[], ARRAY['yoga']::text[]),
  ('Warrior III', ARRAY['legs','core']::text[], ARRAY['yoga']::text[]),
  ('Triangle Pose', ARRAY['legs','core']::text[], ARRAY['yoga','mobility']::text[]),
  ('Half Moon Pose', ARRAY['legs','core']::text[], ARRAY['yoga']::text[]),
  ('Chair Pose', ARRAY['legs']::text[], ARRAY['yoga','isometric']::text[]),
  ('Eagle Pose', ARRAY['legs','core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Crow Pose', ARRAY['arms','core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Side Crow', ARRAY['arms','core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Headstand', ARRAY['arms','core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Handstand', ARRAY['arms','core','full body']::text[], ARRAY['yoga','isometric']::text[]),
  ('Handstand Hold', ARRAY['arms','core','full body']::text[], ARRAY['isometric']::text[]),
  ('Wall Handstand', ARRAY['arms','core']::text[], ARRAY['isometric']::text[]),
  ('Forearm Stand', ARRAY['arms','core']::text[], ARRAY['isometric']::text[]),
  ('Shoulder Stand', ARRAY['core','full body']::text[], ARRAY['yoga']::text[]),
  ('Plow Pose', ARRAY['back','core','legs']::text[], ARRAY['yoga']::text[]),
  ('Wheel Pose', ARRAY['full body','back']::text[], ARRAY['yoga','mobility']::text[]),
  ('Bow Pose', ARRAY['back','core','legs']::text[], ARRAY['yoga']::text[]),
  ('Locust Pose', ARRAY['back','core','legs']::text[], ARRAY['yoga','isometric']::text[]),
  ('Reclined Hero', ARRAY['legs']::text[], ARRAY['mobility','yoga']::text[]),
  ('Hero Pose', ARRAY['legs']::text[], ARRAY['yoga']::text[]),
  ('Lotus Pose', ARRAY['legs']::text[], ARRAY['yoga']::text[]),
  ('Half Lotus', ARRAY['legs']::text[], ARRAY['yoga']::text[]),
  ('Easy Pose', ARRAY['legs','other']::text[], ARRAY['yoga']::text[]),
  ('Sun Salutation A', ARRAY['full body']::text[], ARRAY['yoga','mobility','cardio']::text[]),
  ('Sun Salutation B', ARRAY['full body']::text[], ARRAY['yoga','mobility','cardio']::text[]),
  ('Vinyasa Flow', ARRAY['full body']::text[], ARRAY['yoga','mobility']::text[]),
  ('Chaturanga', ARRAY['arms','chest','core']::text[], ARRAY['yoga','calisthenics']::text[]),
  ('Side Angle Pose', ARRAY['legs','core']::text[], ARRAY['yoga','mobility']::text[]),
  ('Reverse Warrior', ARRAY['legs','core']::text[], ARRAY['yoga']::text[]),
  ('Goddess Pose', ARRAY['legs','core']::text[], ARRAY['yoga','isometric']::text[]),
  ('Garland Pose', ARRAY['legs']::text[], ARRAY['yoga','mobility']::text[]),
  ('Wide-legged Forward Fold', ARRAY['legs','back']::text[], ARRAY['yoga','mobility']::text[]),
  ('Standing Split', ARRAY['legs']::text[], ARRAY['yoga','mobility']::text[]),
  ('Dancer Pose', ARRAY['legs','core','full body']::text[], ARRAY['yoga','mobility']::text[]),
  ('Boxing Jab', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Boxing Cross', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Boxing Hook', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Boxing Uppercut', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Punch Combo', ARRAY['arms','full body']::text[], ARRAY['cardio']::text[]),
  ('Front Kicks', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Side Kicks', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Roundhouse Kicks', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Back Kicks', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Knee Strikes', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Mule Kicks', ARRAY['legs','arms','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Squat to Press', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Renegade Rows', ARRAY['arms','back','core']::text[], ARRAY['resistance']::text[]),
  ('Devil Press', ARRAY['full body']::text[], ARRAY['resistance','cardio']::text[]),
  ('Man Maker', ARRAY['full body']::text[], ARRAY['resistance','cardio']::text[]),
  ('Wall Walks', ARRAY['arms','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Handstand Push-ups', ARRAY['arms','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Pike Walks', ARRAY['arms','core']::text[], ARRAY['mobility']::text[]),
  ('Crab Reaches', ARRAY['core','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Spiderman Lunges', ARRAY['legs','core']::text[], ARRAY['mobility']::text[]),
  ('Walking Knee Hugs', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Walking Quad Stretch', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('Toy Soldiers', ARRAY['legs']::text[], ARRAY['mobility']::text[]),
  ('A-Skips', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('B-Skips', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Carioca', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Lateral Bounds', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Broad Jumps', ARRAY['legs','full body']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Pogo Jumps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Single-leg Hops', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Toe Taps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Heel Taps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Side-to-side Hops', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Speed Skaters', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Bear Hold', ARRAY['core','full body']::text[], ARRAY['isometric']::text[]),
  ('Side Plank Hold', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('L-sit Hold', ARRAY['core','arms']::text[], ARRAY['isometric']::text[]),
  ('Hollow Body Hold', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Arch Hold', ARRAY['back','core']::text[], ARRAY['isometric']::text[]),
  ('Glute Bridge Hold', ARRAY['legs','core']::text[], ARRAY['isometric']::text[]),
  ('Wall Sit Hold', ARRAY['legs']::text[], ARRAY['isometric']::text[]),
  ('Horse Stance', ARRAY['legs']::text[], ARRAY['isometric']::text[]),
  ('Iron Cross Hold', ARRAY['arms','core']::text[], ARRAY['isometric']::text[]),
  ('Static Lunge', ARRAY['legs']::text[], ARRAY['isometric']::text[]),
  ('Static Squat', ARRAY['legs']::text[], ARRAY['isometric']::text[]),
  ('Reverse Snow Angels', ARRAY['back','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Prone Y Raise', ARRAY['back','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Prone T Raise', ARRAY['back','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Prone W Raise', ARRAY['back','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Scapular Pulls', ARRAY['arms','back']::text[], ARRAY['calisthenics']::text[]),
  ('Scapular Push-ups', ARRAY['arms','chest','back']::text[], ARRAY['calisthenics']::text[]),
  ('Dead Hangs', ARRAY['arms','back']::text[], ARRAY['isometric']::text[]),
  ('Active Hangs', ARRAY['arms','back']::text[], ARRAY['isometric']::text[]),
  ('Tuck Front Lever', ARRAY['arms','back','core']::text[], ARRAY['isometric']::text[]),
  ('Tuck Back Lever', ARRAY['arms','back','core']::text[], ARRAY['isometric']::text[]),
  ('Skin the Cat', ARRAY['arms','back','core']::text[], ARRAY['calisthenics']::text[]),
  ('Muscle-ups', ARRAY['arms','back','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Front Lever', ARRAY['arms','back','core']::text[], ARRAY['isometric']::text[]),
  ('Back Lever', ARRAY['arms','back','core']::text[], ARRAY['isometric']::text[]),
  ('Planche Lean', ARRAY['arms','chest','core']::text[], ARRAY['isometric']::text[]),
  ('Tuck Planche', ARRAY['arms','chest','core']::text[], ARRAY['isometric']::text[]),
  ('Box Step-overs', ARRAY['legs','full body']::text[], ARRAY['cardio','calisthenics']::text[]),
  ('Step-up Knee Drive', ARRAY['legs','core']::text[], ARRAY['calisthenics','cardio']::text[]),
  ('Reverse Lunge to Knee Drive', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Lunge with Twist', ARRAY['legs','core']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Squat to Lateral Raise', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Squat to Curl', ARRAY['full body']::text[], ARRAY['resistance']::text[]),
  ('Push-up to T-rotation', ARRAY['arms','chest','core']::text[], ARRAY['calisthenics']::text[]),
  ('Cossack to Cossack', ARRAY['legs']::text[], ARRAY['mobility','calisthenics']::text[]),
  ('Crab to Plank', ARRAY['core','full body']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Beast to Crab', ARRAY['core','full body']::text[], ARRAY['calisthenics','mobility']::text[]),
  ('Single-leg Romanian Deadlift', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Marching in Place', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('March with Knee Lift', ARRAY['legs','core']::text[], ARRAY['cardio']::text[]),
  ('Cross Punches', ARRAY['arms','core']::text[], ARRAY['cardio']::text[]),
  ('Ski Jumps', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Football Drills', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Ladder Drills', ARRAY['legs','full body']::text[], ARRAY['cardio']::text[]),
  ('Box Squat', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Pause Squat', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Kang Squat', ARRAY['legs','back']::text[], ARRAY['resistance','mobility']::text[]),
  ('Cyclist Squat', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Heels-elevated Squat', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Sissy Squat', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Shrimp Squat', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Nordic Curl', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Reverse Nordic Curl', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Sliding Leg Curl', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Single-leg Bridge', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('March Bridge', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Banded Walks', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Lateral Banded Walks', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Banded Clamshells', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Standing Clamshells', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Quadruped Hip Extension', ARRAY['legs','core']::text[], ARRAY['calisthenics']::text[]),
  ('Reverse Hyperextensions', ARRAY['back','legs']::text[], ARRAY['calisthenics']::text[]),
  ('Back Extensions', ARRAY['back','core']::text[], ARRAY['calisthenics']::text[]),
  ('Hyperextensions', ARRAY['back','core']::text[], ARRAY['calisthenics']::text[]),
  ('Glute Ham Raise', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Goblet Reverse Lunge', ARRAY['legs']::text[], ARRAY['resistance']::text[]),
  ('Box Pistol Squat', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Assisted Pistol Squat', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Side Lunge to Curtsy', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Pulse Squats', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Pulse Lunges', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Plank to Push-up', ARRAY['arms','chest','core']::text[], ARRAY['calisthenics']::text[]),
  ('Reaching Plank', ARRAY['core','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Plank with Leg Lift', ARRAY['core','legs']::text[], ARRAY['calisthenics']::text[]),
  ('Plank with Arm Lift', ARRAY['core','arms']::text[], ARRAY['calisthenics']::text[]),
  ('Spider Plank', ARRAY['core','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Stir the Pot', ARRAY['core','full body']::text[], ARRAY['isometric']::text[]),
  ('Pallof Press', ARRAY['core']::text[], ARRAY['isometric']::text[]),
  ('Dragon Flag', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Windshield Wipers', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Toe-to-bar', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Knees-to-elbows', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Hanging Knee Raises', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Cable Wood Chops', ARRAY['core']::text[], ARRAY['resistance']::text[]),
  ('Standing Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Standing Bicycles', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Standing Oblique Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Side Bend Crunches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Toe Reaches', ARRAY['core']::text[], ARRAY['calisthenics']::text[]),
  ('Sit-up to Stand', ARRAY['core','full body']::text[], ARRAY['calisthenics']::text[]),
  ('Hand Release Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['calisthenics']::text[]),
  ('Tempo Push-ups', ARRAY['arms','chest']::text[], ARRAY['calisthenics']::text[]),
  ('Plyo Push-ups', ARRAY['arms','chest']::text[], ARRAY['calisthenics']::text[]),
  ('Box Push-ups', ARRAY['arms','chest']::text[], ARRAY['calisthenics']::text[]),
  ('Tiger Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['calisthenics']::text[]),
  ('Pseudo Planche Push-ups', ARRAY['arms','chest','core']::text[], ARRAY['calisthenics']::text[]),
  ('Eccentric Pull-ups', ARRAY['arms','back']::text[], ARRAY['calisthenics']::text[]),
  ('Tempo Squats', ARRAY['legs']::text[], ARRAY['calisthenics']::text[]),
  ('Pause Push-ups', ARRAY['arms','chest']::text[], ARRAY['calisthenics']::text[]),
  ('Cooldown', ARRAY['other']::text[], ARRAY['other']::text[]),
  ('Warmup', ARRAY['full body']::text[], ARRAY['mobility']::text[]),
  ('Stretching', ARRAY['full body']::text[], ARRAY['mobility']::text[]),
  ('Recovery', ARRAY['other']::text[], ARRAY['other']::text[]),
  ('Water Break', ARRAY['other']::text[], ARRAY['other']::text[]);